---
title: "Logistic Regression"
author: "Justin Besteman"
date: "April 8, 2017"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Clean up the past

```{r clean-up, echo=TRUE}

# Clean up
rm(list = ls())

```

### Loading Libraries

```{r libraries, echo=TRUE, message=FALSE, warning=FALSE}
# Used to read in the data est
library(readr)

# Used to make the graph of the ROCR
library(ROCR)

```

### Reading in the data of PassFail.dat

```{r part-a , echo=TRUE}

# Loading in Data
theData <- read_delim(
  "~/Desktop/code/topics/logistic-regression/PassFail.dat",
  " ",
  escape_double = FALSE,
  col_names = FALSE,
  col_types =
    cols(
      X1 = col_skip(),
      X10 = col_skip(),
      X12 = col_skip(),
      X14 = col_skip(),
      X2 = col_skip(),
      X4 = col_skip(),
      X6 = col_skip(),
      X8 = col_skip()
    ),
  na = "null",
  trim_ws = TRUE
)

# Making the theData into a data.frame
PassFail <- data.frame(theData)

# Renaming columns
colnames(PassFail) <- c("y", "x1", "x2", "x3", "x4", "x5", "x6")

```


### Number of Observations


```{r  part-b}

# Number of Observation will hold the number of observation
numberOfObservation <-  nrow(PassFail)

numberOfObservation

```


### Making sample data and test data


```{r part-c}

# Setting the set seed of the random number generator for consistent testing
set.seed(123321)

# Making index a vector of that holds the number of observation 
# I.E (1,2,3, ..... , 10000)
index <- c(1:numberOfObservation)

# Setting random6000 to the random sample of 6000
# Using sample() to grab 6000 random sample
random6000 <- sample(index, numberOfObservation * .60)

# trainingSamplePassFail to random sample of indices of index and 
# pulling then from PassFail data
trainingSamplePassFail <- PassFail[random6000 ,]

# testData will hold the rest of the 4000 data sampl
testData <-  PassFail[-random6000 ,]


```


### Running GLM


```{r part-d}

# Running glm on the trainSamplePassFail data
# Formula y = x1 + x2 + x3 + x4 + x5 + x6
model <- glm(y  ~ . , data = trainingSamplePassFail , family = binomial(link = "logit"))

model

```


### Observation scoring the test data


```{r part-e}

# Testing the prediction

# Testing the model against the testData
results <- predict(model, testData ,type='response')

# Using ifelse to test it best on .5 
results <- ifelse(results > 0.5,1,0)

# Finding the error
error <- mean(results != testData$y)

error

# Showing the Accuracy of the model
accuracy <- 1 - error

accuracy

```


### Making the plot of the curve of the ROCR


```{r part-f}
# Using the ROCR Package here


p <- predict(model,testData, type="response")
pr <- prediction(p, testData$y)
prf <- performance(pr, measure = "tpr", x.measure = "fpr")

auc <- performance(pr, measure = "auc")
auc <- auc@y.values[[1]]
auc

# Ploting the curve
plot(prf)

# Plotting the random guessing line
abline(a = 0 , b = 1 , lty = 3)

```